export type QualificationState='qualified'|'stale'|'unknown'|'not_ready'|'blocked';
export type EvidenceClaim={field:string;value:string;source_url:string;quote:string};
export type Source={id:string;path_id:string;url:string;fingerprint:string;excerpt:string;retrieved_at:number};
export type Action={id:string;description:string;task_id?:string;effects:'read'|'write'|'mixed'|'destructive'|'unknown';required_scopes?:string[];limitations?:string[];source_refs?:string[];input_schema?:Record<string,unknown>;output_schema?:Record<string,unknown>};
export type PathDeclaration={kind:'api'|'mcp'|'cli'|'other';target:string;documentation_url:string;purpose:string;purpose_summary?:string;method:string;authentication:{method:string;instructions:string};prerequisites:string;relationship:'first_party'|'independent_adapter';evidence:{target:string;purpose:string;method:string;authentication:string;prerequisites:string};metadata:{runtime?:string;connection?:ConnectionExample;tasks?:string[];actions?:Action[];claims?:EvidenceClaim[];access?:{setup:'none'|'required'|'interactive'|'unknown';required_scopes:string[];human_steps:string[]};capabilities?:string[];limitations?:string[];pricing?:{plan?:string;currency?:string;amount?:number;unit?:string;pricing_url?:string};permissions?:{scopes:string[];effects?:'read'|'write'|'mixed'|'unknown'};[key:string]:unknown}};
export type ConnectionExample={command:string;description:string;source_url:string;quote:string;expected_response?:string};
export type ConnectionGuide={kind:PathDeclaration['kind'];target:string;purpose:string;method:string;authentication:PathDeclaration['authentication'];prerequisites:string;documentation_url:string;setup?:PathDeclaration['metadata']['access'];cli?:{package:string;version?:string;platforms?:string[];runtime?:string};configuration?:string;example?:ConnectionExample;actions?:Action[];permissions?:PathDeclaration['metadata']['permissions'];pricing?:PathDeclaration['metadata']['pricing'];limitations?:string[]};
export type PathView={connection:ConnectionGuide;documentation:{label:string|null;checked_at:string|null};operational_status:{observation_id:string;path_revision:number;report:Record<string,unknown>}|null;recovery_actions:{action:string;label:string;url:string;method:'GET'|'POST';authentication_required:boolean}[];path_id:string;revision:number;kind:PathDeclaration['kind'];target:string;declaration:PathDeclaration;qualification:{status:QualificationState;reason_codes:string[];checked_at:string|null;valid_until:string|null;checked_scope:string[];provider_operations_tested:false};source_ids:string[];sources:Source[];setup:{status:'none'|'required'|'interactive'|'unknown';basis:string};task_ids:string[];task_basis:string;task_labels:{id:string;basis:string}[];reason_descriptions:string[];latest_successful_assessment:Record<string,unknown>|null;latest_attempt:Record<string,unknown>|null;claim_checks:Record<string,unknown>;observations:Record<string,unknown>[]};
export type SiteView={schema_version:string;service_id:string;revision:number;identity:{name:string;canonical_url:string;categories:string[];publisher_claim:'claimed'|'claim_expired'|'unclaimed'};description:string;description_basis:string;entity:{type:'application'|'service'|'organization';aliases:string[];operator?:{name:string;url:string;source_url:string;quote:string};builder_agent_id?:string;coverage?:string};paths:PathView[];community:Record<string,unknown>;entry_id:string;created_at:number;updated_at:number;profile_url:string;api_url:string;submitted_by:Record<string,unknown>|null};
export type CatalogueQuery={query?:string;interface?:PathDeclaration['kind'];category?:string;task?:string;status?:QualificationState;cursor?:string;limit?:number};
export type CatalogueResult={schema_version:string;results:SiteView[];next_cursor:string|null;scope:string;filters:CatalogueQuery};
export type SearchResult={schema_version:string;results:(SiteView&{matched_path_ids:string[];compatibility:'compatible'|'requires_setup';ranking:{version:string;reasons?:string[];[key:string]:unknown};connection_paths?:({path_id:string}&ConnectionGuide)[];setup_fit?:string;compatibility_basis?:string})[];next_cursor:string|null;applied_query:Record<string,unknown>;guidance:SearchGuidance|null;interpreted_intent?:{terms:string[];task_ids:string[]};provider_operations_tested:false};
export type FilterResult={schema_version:string;results:{input_url:string;resolved_service_id?:string;included:boolean;qualification:QualificationState;compatibility:string;reason_codes:string[];matched_paths?:PathView[];community?:Record<string,unknown>}[];provider_operations_tested:false};

export type SearchGuidance={message:string;additional_known_matches:number;without_current_documentation:number;truncated:boolean;alternatives:{service_id:string;name:string;profile_url:string;matched_path_ids:string[]}[];suggested_tasks:{id:string;name:string;url:string}[];catalogue_url:string;taxonomy_url:string;discovery_query?:Record<string,unknown>};
export type ValidationResult={valid:boolean;schema_valid:boolean;publication_checked:false;issues:{path:(string|number)[];code:string;message:string}[];document_checks?:{path_index:number;field:string;status:string;source_url:string}[];normalized_submission?:unknown;next_step?:string;source_basis?:string};
export type ComparisonResult={schema_version:string;results:SiteView[];resolutions:{input:string;status:'resolved'|'ambiguous'|'not_found';candidates:{service_id:string;name:string;url:string}[]}[]};

export type CompactPath={path_id:string;revision:number;connection:Omit<ConnectionGuide,'actions'|'example'|'pricing'|'limitations'>;qualification:PathView['qualification'];operational_status:PathView['operational_status'];task_matches:{id:string;basis:string}[];actions:Action[];constraints:{runtime:string|null;pricing:PathDeclaration['metadata']['pricing']|null;rate_limits:unknown;limitations:string[]|null};evidence:Omit<Source,'excerpt'|'path_id'>[];detail_url:string;[key:string]:unknown};
export type CompactSite={service_id:string;revision:number;entry_id:string;identity:Pick<SiteView['identity'],'name'|'canonical_url'|'publisher_claim'>;selected_path:CompactPath|null;alternative_paths:{path_id:string;revision:number;kind:string;detail_url:string}[];detail_url:string;profile_url:string;discussion_url:string};
export type CompactSearchResult=Omit<SearchResult,'results'>&{view:'connect';results:CompactSite[];pagination?:{reason:'response_budget';max_bytes:number;returned_results:number;requested_limit:number}};
